### ISSUE TITLE
 Toast. 'PortalStateContext' cannot be null

### ISSUE THREAD

**Issue by Aleksandern** [tamagui/tamagui#1449]
I'm trying to use Toast

`TamaguiProvider` and `ToastProvider` are added.

With `ToastViewport` I get the error:
`
Error: 'PortalStateContext' cannot be null, please add 'PortalProvider' to the root component.
`

-----
"react-native": "0.71.10",
"@tamagui/toast": "^1.43.13",
"tamagui": "^1.43.13",

**Comment by quynguyencanalcircle** [comment]
@Aleksandern Hi, I got the same problem. How do you fix them?

**Comment by Aleksandern** [comment]
Hi @quynguyencanalcircle,

Just wrap your app with `PortalProvider` like this:
```
    <TamaguiProvider
      config={config}
      defaultTheme={themeProv}
    >
      <PortalProvider>
          {screen}
      </PortalProvider>
    </TamaguiProvider>
```

**Comment by amoghkulkarnifr** [comment]
Hello, I am facing the same issue and the error still persists even if I wrap my app with `PortalProvider` as suggested here. 

I would love to have some pointers on how to debug this issue.

**Comment by j3sch** [comment]
> Hello, I am facing the same issue and the error still persists even if I wrap my app with `PortalProvider` as suggested here.
> 
> I would love to have some pointers on how to debug this issue.

I have the same problem. I used Nexjts and Expo before and everything worked fine. Now I have switched to Expo Router 3 and I am facing this problem.  Have you found a solution?

**Comment by amoghkulkarnifr** [comment]
I am assuming you continue to face the problem even after wrapping your app in the `PortalProvider` (which is the accepted solution for this). If you haven't done that, I'd suggest you try that first.

If you continue to face issue even after using `PortalProvider` (as in my case) - I found that I was facing this problem because my `tamagui` package version and `@tamagui/toast` package version did not match. As soon as I fixed that, the problem went away. 

I'd suggest taking a closer look at the versions in your `package.json` since you just changed to different packages, and it stopped working.

**Comment by olehlavryk** [comment]
@amoghkulkarnifr Could you share `tamagui `and `@tamagui/toast` version because i have the same issue

**Comment by amoghkulkarnifr** [comment]
Sure. I am not working with the most recent tamagui stack, but I got it working with `^1.90.2` for both `tamagui` and `@tamagui/toast` in my package.json.

**Comment by olehlavryk** [comment]
@amoghkulkarnifr Thanks it works, I'm using `^1.91.4` for both packages in my package.json.
I've got a new one error messages `TypeError: Cannot read properties of undefined (reading 'delay')`
![image](https://github.com/tamagui/tamagui/assets/6538381/a7ac1e5e-633c-4755-9681-1bc9df54bf12)
