### ISSUE TITLE
Question: Is Tamagui free to use without getting the pro version?

### ISSUE THREAD

**Issue by dnaicker86** [tamagui/tamagui#1465]
### Tamagui Version

```markdown
1.0
```

### Reproduction

```markdown
1.0
```

**Comment by flexbox** [comment]
Hello @dnaicker86 

What do you mean with "pro version"?

You can create a new project today with
```
npm create tamagui@latest
```

There is a "pro version" called `takeout` you can use as an opinionated template with supabase, and other tools
```
yarn create tamagui --template takeout
```
but it's more a starter project Vs. a pro version

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
