### ISSUE TITLE
Set `mediaQueryDefaultActive` in a next middleware

### ISSUE THREAD

**Issue by ha3** [tamagui/tamagui#1611]
### Current Behavior

I have three different breakpoints for my site, `small`, `medium`, and `large`. My layout differs greatly according to the breakpoint. During SSR, it always assumes `small` breakpoint, hence renders accordingly. This causes a layout shift for non-small devices.

A solution for this could be to determine the approximate breakpoint in a Next middleware using user agent info. On tamagui side, I need to be able to set the corresponding media during SSR. My first thought was to create a custom `createMedia` for this, by inheriting `window.matchMedia` on the client, reading to some external data set by the middleware in the server. But later I discovered the `mediaQueryDefaultActive` API, which seems to be suited for this job. However, setting it dynamically doesn't seem to be working. It only uses the initial static value in the config. Calling `configureMedia` after setting doesn't help also.

@natew what's your opinion on this? Would you consider supporting this use case if it doesn't already?

### Tamagui Version

```markdown
v1.58.3
```

### Reproduction

```markdown
- Create a tamagui config
- Outside the config declaration, set a valid object to `config.mediaQueryDefaultActive`
- Call `configureMedia` with the new config
- Observe that media values in `useMedia` don't change accordingly in SSR
```

**Comment by natew** [comment]
I'd be open to supporting this, I assume the reason you can't just pass it directly to createTamagui is because we basically need createTamagui to be exported and not generated for typescript purposes? I think you could still get TS support while having your own wrapper around createTamagui that supports accepting a userAgent and generating a new config.

Lmk if that makes sense. Right now configureMedia is more of an internal thing, but we could figure out a way to expose this.

**Comment by natew** [comment]
try out 1.63 it has a couple changes that i think make this work, if not we can re-open
