### ISSUE TITLE
The custom SizableText color is ignored depending on the props order

### ISSUE THREAD

**Issue by razin-ivan98** [tamagui/tamagui#1628]
### Current Behavior

**Prerequisites:**
- font defined by createFont, like that:
```
const bodyFont = createFont({
  family: 'Sans',
  color: {
    true: 'black',
  },
  size: {
    s: 12,
    m: 14,
    true: 14,
  },
  lineHeight: {
    s: 12,
    m: 18,
    true: 18,
  },
  weight: {
    s: '400',
    true: '500',
  },
})
```
- SizableText used with both color and size props, like that:
```
<SizableText fontFamily="$body" color="red" size="$s">
    THIS TEXT HAS WRONG COLOR
</SizableText>
```

**Current behaviour:**
in this case, red color prop is ignored, but it works correctly if color and size props are swapped, like that:
```
<SizableText fontFamily="$body" size="$s" color="red">
    THIS TEXT HAS VALID COLOR
</SizableText>
```

### Expected Behavior

color prop behaviour works stable and correctly without props order dependency

### Tamagui Version

```markdown
1.61.1
```

### Reproduction

[CodeSandbox fork](https://codesandbox.io/p/sandbox/mutable-pine-t54yg3?file=%2Fpackages%2Fui%2Fpackage.json%3A1%2C1)

```markdown

Both SizableText components with valid and wrong colors are presented on HomeScreen
bodyFont is defined by createFont at tamagui.config.js
```

**Comment by nderscore** [comment]
You have defined a default color as part of your font definition: (true is the default size token)

```diff
const bodyFont = createFont({
  family: 'Sans',
+  color: {
+    true: 'black',
+  },
```

Which means setting a font `size` also applies a `color` style.

So what you're seeing is the expected behavior.

[Prop order is important by design](https://tamagui.dev/docs/intro/props#order-is-important).

**Comment by natew** [comment]
We can also make the size variant act in a way that it respects prior props, because variants take in prior props. I think in this case `size` sort of implies only size-related things, but it just grabs every possible font token. In a way its a bit mis-named, so I can make this change to respect color.

**Comment by natew** [comment]
Making that change in next minor, 6b3824d353dcb3c2e340b0756d8ff39a1cc57808
