### ISSUE TITLE
1.70 regression causing wrong Button text color

### ISSUE THREAD

**Issue by vonovak** [tamagui/tamagui#1746]
### Current Behavior

In 1.69.1 I have the following code yielding this result

```
import { Text } from 'react-native'

<Button >
    <Text>English</Text>
  </Button>
```

![IMG_9422](https://github.com/tamagui/tamagui/assets/1566403/9dcb0ec4-c171-43fb-aff1-ea0813a83af1)

on 1.73 (I believe it changed in 1.70) this yields the following 

![IMG_9420](https://github.com/tamagui/tamagui/assets/1566403/df41375d-1e16-41ee-87f5-0e0f1a8e68c6)

You might be wondering why I'm nesting the `Text` like that. In fact, I'm using the `Trans` component from [Lingui](https://lingui.dev/ref/react#rendering-translations) (which is also used on the uniswap frontend btw) which effectively adds that nested `Text`. 

Adding that nesting should not matter for styling, react native just takes the styles of the parent `Text`.
I can work around this issue but would appreciate if this worked like previously, because that's how RN handles nested text. This issue is likely going to arise in other contexts as well.

thank you!

### Expected Behavior

I expect the new versions of the package to behave like 1.69.

### Tamagui Version

```markdown
1.73
```

### Platform (Web, iOS, Android)

```markdown
reproduced on iOS, didn't try other platforms
```

### Reproduction

```markdown
import { Text } from 'react-native'

<Button >
    <Text>English</Text>
  </Button>
```
```


### System Info

_No response_

**Comment by natew** [comment]
The Button component only wraps props.children in a ButtonText component if they are strings, once you wrap the inner contents with Text our Button no longer wraps a ButtonText around it so it no longer sets the color for them.

This hasn't changed though across versions, even prior versions had this logic to only wrap them if they are strings. We have a `noTextWrap` prop, I wish now it was a `textWrapStrategy` prop so we could add something like `force` to it, but I'm really curious how that could even work before since I don't see how it would.

**Comment by natew** [comment]
Verified on 1.70 and this is doing the same thing there. If you can isolate when this was working I'd be really curious as it may have actually been a bug where we wrapped Text on accident. Which should break other things, but would be interesting to see if it was there nonetheless.
