### ISSUE TITLE
react-native-reanimated pinned at 3.4.1 breaks expo go kitchen sink

### ISSUE THREAD

**Issue by benschac** [tamagui/tamagui#1877]
try running kitchen sink with expo go, it doesn't work.

logging an issue to not forget about it.

I saw in https://github.com/tamagui/tamagui/blob/master/package.json#L84

we are explictly pinning to 3.4.1. Seems like kitchen sink is picking up 3.4.1 instead of 3.3.0 that expo requires.

@natew - what do you think is the best solution here? was thinking maybe breaking kitchen sink out and having some way to symlink just off the top of my head? Or is there a better way to isolate deps inside the monorepo?

**Comment by natew** [comment]
i use a custom built version of kitchen sink so we can test everything incl the various native integrations (thus kitchen sink), we could probably pin down to match latest expo but we'd still need a custom build to run it i believe as metros eager require eval errors due to demos folder being glob imported.

I don't want to sacrifice that ease of testing all the demos or add much cruft with supporting go if we don't really need to.

**Comment by benschac** [comment]
Yeah, that makes sense. My goal is that we test everything and don't leave expo out. I only really harp on expo go because it's the lowest barrier of entry to folks using tamagui.

**Comment by natew** [comment]
There’s definitely a way to make it work it can just load a different entry and use specific imports of packages.
