### ISSUE TITLE
CodeSandbox Link in Issue Template is not working

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#2075]
Or at least I can't figure out how to get it to work 🤷 

I've tried:
❌ Running it as-is by following the link
❌ Forking onto my account
❌ Following the CodeSandbox prompts to upgrade to a DevBox to run commands

When debugging a different Tamagui issue, I tried out Gitpod, which seemed to work much better. While this isn't an endorsement for them and would advise the Tamagui project to do whatever works best, it is worth noting that Gitpod has an Open Source program as well: https://www.gitpod.io/discover/opensource

Let me know how to best move this forward as I'd like to test out a few behaviours I'm seeing to determine if it's an actual Tamagui issue or an issue with my setup

Thanks!

**Comment by natew** [comment]
Probably regressed at some point, thanks for notifying. Gitpod is fine if we get something together on it.

**Comment by tazsingh** [comment]
Yeah 😅

Reporting back, I tried Stackblitz with more success than CodeSandbox but it's still having issues related to Yarn. Saving the link here in case other folks have more success moving it forward: https://stackblitz.com/github/tamagui/starter-free

**Comment by jmatsushita** [comment]
Same issue here trying to create a minimal reproducer for a potential issue. 

Seems the problem is that codesandbox by default tries to use `pnpm` instead of `yarn`. 

Adding a `.codesandbox/tasks.json` file in the repo should fix that:
```json
{
  // These tasks will run in order when initializing your CodeSandbox project.
  "setupTasks": [
    {
      "name": "Install Dependencies",
      "command": "yarn install"
    }
  ],

  // These tasks can be run from CodeSandbox. Running one will open a log in the app.
  "tasks": {
    "install": {
      "name": "install dependencies",
      "command": "yarn install"
    },
    "Development": {
      "name": "Development",
      "command": "yarn web",
      "runAtStart": true,
      "preview": {
        "port": 3000
      }
    }
  }
}
``` 

There's a more complete official sandbox template for react-native-expo here which could be used for further improvement for the tamagui starter sandbox https://github.com/codesandbox/sandbox-templates/tree/main/react-native-expo

**Comment by jmatsushita** [comment]
Looks like it's also needed to specify a `.devcontainer/devcontainer.json` for the sandbox to automatically start as a `devbox`. So for instance opening this `devcontainer` branch on my fork does the right thing https://codesandbox.io/p/devbox/github/jmatsushita/starter-free/tree/devcontainer I'll modify the PR to include this.

**Comment by jmatsushita** [comment]
Alternatively, this is a devbox version based of the tamagui expo-router template:
```bash
npm create tamagui@latest --template expo-router
```

And using the `.codesandbox` and `.devcontainer` from the `react-native-expo` sandbox template (modified for `yarn`). https://github.com/jmatsushita/tamagui-expo-router-devbox feel free to just copy it into the `tamagui` namespace if you want.

https://codesandbox.io/p/devbox/github/jmatsushita/tamagui-expo-router-devbox

Turns out on first launch it reproduced this bug https://github.com/tamagui/tamagui/issues/2230 
```
Web Bundling failed 69519ms (node_modules/expo-router/entry.js)
Unable to resolve "/workspaces/sandbox/.tamagui/css/apptabslayouttsx.css" from "app/(tabs)/_layout.tsx"
λ Bundling failed 69561ms (node_modules/expo-router/node/render.js)
λ node_modules/expo-router/node/render.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1357/1367)
Error: ENOENT: no such file or directory, open '/workspaces/sandbox/node_modules/@expo/server/src/index.ts'
```

But reloading the preview fixed it.
