### ISSUE TITLE
useTheme returns ugly values

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#212]
**Describe the bug**
Before reading the docs about the `useTheme` hook, I thought that it was just like others themable libraries and that it returned the theme tokens, instead by logging it I saw that it actually is a key/value pair of objects of type VariableValue (defined in @tamagui/core/types/createVariable.d.ts).

Giving for example the following

```typescript
import { useTheme } from 'tamagui';

const MyComponent=()=>{
    const theme = useTheme();
    console.log(theme["$blue1"])

}

```

this is what will be logged

![Screenshot 2022-09-17 at 16 19 58](https://user-images.githubusercontent.com/5955338/190861788-07c5c18a-2b51-45cc-9257-d54a23be56b5.png)

And, most important, it does not contain custom defined tokens.

The `getTokens()` function instead (documented here https://tamagui.dev/docs/core/exports#gettokens) returns the correct values, but with the same very bad usability. 

It would be very useful to have easy access to theme tokens to be used where needed

**Comment by natew** [comment]
Do you mean you want the raw values? It should allow `non-$` so `useTheme().blue1`, if that's broken I can fix.

But also you want to return `.val` from that? The reason it returns `Variable` type objects is because native needs to get `val` while web often wants to get `variable` to be faster. There's no "right" answer there, so you can do `getVariableValue(useTheme().blue1)`.

But I do think we could make this nicer in a few ways. I'll think over how.

**Comment by natew** [comment]
So looking this over, we can probably improve things, but it's good to know:

Theme != Tokens, Tokens never change (which is why `getTokens` not `use`) whereas Theme can change throughout the tree.

The VariableValue is necessary because web and native need differing things, but web *also* needs to get the real value, so you need access to variable + value. I've tried working around this with an inverse lookup, but that only works if you never have duplicate values for any theme key, which actually can happen quite often.

If you do `getVariableValue(useTheme().background)` it is smart about which platform to resolve to.

I used to have a modified `toString()` so you could do `useTheme().background.toString` and so it auto-coerced, but React Server Components doesn't support serializing classes, so I changed them to objects. That is a bummer.

`getTokens` acts pretty consistently though, same VariableValue being returned and it matches your tokens exactly.

Not sure what the right way to go about it is, any option will either have a lot of magic or be more awkward like this. It's possible I could find a way to decorate the objects with RSC, I'll check that, but you'd still at best have toString auto coerce, or maybe an explicit `.get()`. But not sure how possible that is.

Open to any ideas.

**Comment by apperside** [comment]
Hello @natew ,
I surely understand your points.
Struggling with cross platform compatibility is alway a big deal, and there are tons of things to consider.
That being said, I would start from the highest level of the problem: it is not uncommon the need to access a theme variable in your components, and this is usually done in other libraries through the `useTheme` hook.
Let say for now that is ok doing useTheme().background.value, but the problem is that custom theme variables are retuned from the `useTheme()` hook, but typescript does not recognize it. Given for example the following tamagui config:


```typescript
export const config = createTamagui({
  animations,
  defaultTheme: 'light',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes: {
    ...themes,
    light: {
      ...themes.light,
      primaryColor: appTokens.color.primaryColor,
    },
    dark: {
      ...themes.dark,
      primaryColor: appTokens.color.primaryColor,
    },
  },
  tokens:appTokens,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
})

```

If I use useTheme(), I can see the value `colorPrimary` in the returned object, but typescript doesn't. 

Moreover I'd like to discuss the point "Theme != Tokens":

if that's true (and that's reasonable), if I define a custom token like this:

```typescript
export const appTokens = createTokens({
  ...tokens,
  color: {
    ...tokens.color,
    primaryColor: '#EA7C69',
    secondaryColor: '#9288E0',
    myColor: '#E97274',
  },
  size: {
    ...tokens.size,
    sm: 10,
    md: 15,
    lg: 25,
  },
});


export const config = createTamagui({
  animations,
  defaultTheme: 'light',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens:appTokens,
  
})
```

so I declare a token but do not add it to the theme, when I write something like:

<Stack backgroundColor="$primaryColor" />

The token is taken from tokens, not the the theme (since I did not added that token to the theme).

Moreover, in such a situation, if I use `useTheme` the `primaryColor` will not be returned, but I have to use `getTokens()` instead. So the question is: when I pass the name of a token in a `backgroundColor` color prop, from where is it taken?

**Comment by apperside** [comment]
For now I added this custom hook in my app:
```typescript

import { Variable } from '@tamagui/core'
import { useTheme as useTamaguiTheme } from 'tamagui'

type ThemeNames = typeof config.themes
type ThemeType<T extends keyof ThemeNames = 'light'> = typeof config.themes[T]
type ThemeValues<T extends keyof ThemeNames = 'light'> = {
  [key in keyof ThemeType]: Omit<Variable, 'val'> & { val: any }
}
export const useAppTheme = <T extends keyof ThemeNames = 'light'>() => {
  const result = useTamaguiTheme() as any as ThemeValues<T>
  return result
}

```

It can be used the following way:

given the following tamagui configuration:

```typescript
export const config = createTamagui({
  animations,
  defaultTheme: 'light',
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes: {
    ...themes,
    light: {
      ...themes.light,
      ...appTokens.color,
    },
    dark: {
      ...themes.dark,
      ...appTokens.color,
    },
    customTheme: {
      customColor: '#f3f3f3',
    },
  },
  tokens: appTokens,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
})

You can use the hook this way

```

![Screenshot 2022-09-19 at 12 11 21](https://user-images.githubusercontent.com/5955338/190995754-2082b8fe-f968-456f-9031-d0bc1813058c.png)

**Comment by natew** [comment]
This will all be fixed in release going out now, thanks for the heads up.
