### ISSUE TITLE
fontFamily="$mono" warning in Expo

### ISSUE THREAD

**Issue by nephix** [tamagui/tamagui#2623]
### Current Behavior

When using `$mono" as fontFamily there's a warning from Expo:

```
fontFamily ""ui-monospace", "SFMono-Regular", "SF Mono", Menlo, Consolas, "Liberation Mono", monospace" is not a system font and has not been loaded through expo-font.
```

### Expected Behavior

I'm not sure, maybe it's ok to just ignore it? If not, a couple of options:

1. Tamagui is loading the font
2. There's a section in the docs about what fonts to load via `expo-font`

Is there a way to fix that warning? Currently, `expo-font` is loading the following from the docs:

```tsx
const [loaded] = useFonts({
    Inter: require("@tamagui/font-inter/otf/Inter-Medium.otf"),
    InterBold: require("@tamagui/font-inter/otf/Inter-Bold.otf"),
});
```

and in

> node_modules/@tamagui

I can't see another font family from the warning to load

### Tamagui Version

```
^1.95.1
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
<Text fontFamily="$mono">
    Some text
</Text>
```

### System Info

```markdown
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 58.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 4.1.1 - ~/.yarn/bin/yarn
    npm: 10.5.0 - ~/Projects/.../node_modules/.bin/npm
    pnpm: 8.15.3 - ~/Library/pnpm/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
    Watchman: 2024.04.29.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.4.1
  npmPackages:
    typescript: ^5.1.3 => 5.4.5
```

**Comment by FranciscoKloganB** [comment]
I have a similar a issue with `poppins`. I created a `createPoppins` helper exactly like the ones I saw on Tamagui packages and use as `{ fonts: { body } }`. However, I just get a warning and no font changes in the UI:

```bash
fontFamily "$body" is not a system font and has not been loaded through expo-font.
```

I wish the documentation was more explicit on how to customize parts of the custom theme with rich examples on how to use the public APIs. It is difficult to adopt a technology like Tamagui if the documentation does not help you get started, no matter how amazing the tools/features are. I know I can't compare apples to potatoes (web vs. native), especially because I well versed with web, but not with native. However, onboarding `PandaCSS` which has a very similar philosophy to Tamagui, is a breeze. I also faced some challenges on that framework, but mostly on very very advanced use cases. :\

**Comment by nephix** [comment]
But `$mono` is a pre defined tamagui token. Shouldn't it already be included then?

**Comment by SamuraiF0x** [comment]
You still need to load it here instead of `inter`:
```tsx
const [loaded] = useFonts({
    Inter: require("@tamagui/font-inter/otf/Inter-Medium.otf"),
    InterBold: require("@tamagui/font-inter/otf/Inter-Bold.otf"),
});
```

**Comment by natew** [comment]
Yep you do need to load it, config v4 will not have any custom fonts and just use system fonts on each platform.
