### ISSUE TITLE
Tamagui starter crashes with trpc ssr enabled

### ISSUE THREAD

**Issue by hlynurstef** [tamagui/tamagui#270]
**Describe the bug**

I created a new project using the starter:
```
npm create tamagui-app@latest
```

I then implemented nextjs trpc following the following trpc docs: https://trpc.io/docs/v10/nextjs

Setting `ssr: true` in the trpc config will result in the following error:

```
TypeError: dispatcher.useInsertionEffect is not a function
```

![Xnapper-2022-10-07-14 31 37](https://user-images.githubusercontent.com/15615089/194578644-e0dcdb35-88ec-47c3-9bd1-b04b51011487.png)

**To Reproduce**

I've created a repo that can reproduce this error:

1. clone https://github.com/hlynurstef/tamagui-trpc
2. `cd tamagui-trpc`
3. `yarn`
4. `yarn web`
5. Notice that everything runs fine
6. set `ssr: true` in https://github.com/hlynurstef/tamagui-trpc/blob/main/packages/trpc-client/src/client.ts
7. Notice the error

**System Info (please complete the following information):** 

Output of `npx envinfo --system --npmPackages --binaries --browsers`
```
  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.02 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 3.2.3 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.3
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.18.9
    @manypkg/cli: ^0.19.1 => 0.19.1
    @types/react: ^18.0.15 => 17.0.21
    @types/react-native: ^0.69.5 => 0.69.5
    eslint: ^8.21.0 => 8.21.0
    prettier: ^2.7.1 => 2.7.1
    turbo: ^1.4.2 => 1.4.2
    typescript: ^4.7.4 => 4.7.4
```

**Tamagui info**

Paste all the following below:

- [x] yarn.lock or similar https://github.com/hlynurstef/tamagui-trpc/blob/main/yarn.lock
- [ ] If it's a specific file, add `//! debug` to the top (the `!` works in esbuild compiled packages but not necessary always) and include that (only for compiler, but helps to know if it's on or off).
- [ ] Run your server/bundler with `DEBUG=tamagui` and include that output at the bottom.

**Comment by natew** [comment]
This almost always is due to duplicate `react` / `react-dom`, but you do have `resolutions` set... looked into what they are doing with `ssr` and it seems just adds `react-ssr-prepass`.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/12100/198854755-38a6fcba-b61c-4052-96ea-907ee4a9a5b1.png">

Can you check that this react has `useInsertionEffect`? There's got to be some sort of duplicate react getting in there.

**Comment by natew** [comment]
Tried a few things with no luck, not sure what's going on here, something with react-ssr-prepass likely.

**Comment by skyriverbend** [comment]
I think I solved this issue! 

I've submitted a PR to tRPC (trpc/trpc#3343).

Basically, `react-ssr-prepass` hasn't been updated in nearly a year and uses `react-dom-17.0.2` instead of 18, and I think that was causing compatibility issues. I've patched tRPC to use React's `renderToPipeableStream` function instead. 

SSR in Tamagui works fine for me now with this fix.

Hopefully they accept the changes. 🤞

**Comment by skyriverbend** [comment]
Update - the PR didn't make it because it because it would break tRPC compatability with React 16 and 17. Potentially it could make it into the next version of tRPC (11). In the meantime, I'm just using tRPC's [SSG helpers workaround](https://trpc.io/docs/ssg-helpers) and setting `ssr: false`. You still get SSR, it just requires a little bit of duplication in your code.

**Comment by natew** [comment]
Closing as it seems to work
