### ISSUE TITLE
useMedia hook having wrong initial value in some situations

### ISSUE THREAD

**Issue by tlow92** [tamagui/tamagui#2770]
### Current Behavior

1. Using the useMedia hook in a `_layout.tsx` file
2. Having a conditional return above the access of the proxy e.g. `media.sm`
3. In some cases (I was not able to reproduce it yet with the starter template) this leads to the hook not updating correctly after refresh
4. In the provided example code `isLoading` is initialized with true and after some time changes to false.
5. When `media.sm` is accessed before the conditional return it updates correctly e.g. adding `console.log(media.sm)` directly after the hook (which I guess defeats the purpose of static optimizations)

### Tamagui Version

```markdown
1.101.7
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
const {session, isLoading, signOut} = useSession();
const media = useMedia();

if (isLoading) {
  return <Text>Loading...</Text>; // This early return leads to useMedia not updating
}

console.log('media.sm in _layout.tsx', media.sm);
return <Slot />
```

What fixes it:

```
const {session, isLoading, signOut} = useSession();
const media = useMedia();
console.log('media.sm in _layout.tsx', media.sm);

if (isLoading) {
  return <Text>Loading...</Text>; // This early return leads to useMedia not updating
}

return <Slot />
```
```


### System Info

_No response_

**Comment by DMZakaria** [comment]
I am experiencing a similar issue in my project where the navigation menu does not display correctly on the initial page load. When I inspect the hook values, I noticed that the `desktop` state is set to `false`. However, once I resize the layout, the media query starts working correctly. The problem consistently occurs only during the first load of the page, the values properly are not set properly.

The problem occurs on Web and Tamagui version 1.101.7

**Comment by alexthewilde** [comment]
I'm experiencing the same issue with `v1.101.0` (shipping with takeout).

**Comment by natew** [comment]
Looking at this now.

**Comment by natew** [comment]
Is this still happening? I've tried a ton of variations and can't replicate.

**Comment by tlow92** [comment]
@natew I just reverted my temporary fixes  (project is now on 1.104.2) and it seems to be fixed there. Was also not able to reproduce it anymore.

**Comment by DMZakaria** [comment]
Hi @natew 
Yes, I still have the issue on my side, even after the migration to 1.105.4. Is it mandatory to have Next.js 14 for Tamagui latest versions ?

**Comment by DMZakaria** [comment]
@natew I will try to do it before the end of the week.

**Comment by tlow92** [comment]
Just wanted to confirm that in another case I now still face the issue. I still didn't figure out what exactly is different in this scenario. 

It's also a case of conditional return statement and if media.gtSm is access before the condition it works fine. Will try to reproduce with starter.

**Comment by face** [comment]
@natew not sure if this helps i see it on every hard reload on web.

i put some debugging, and the issue is a race condition where useMedia state still has default state when my component  ounts and renders.   internal getSnapshot updates don't cause my component to re-render.    My component mounts, and then it renders in the client with the initalState defaults.  Then useMedia has another snapshot update, and it's internalState get's set.   my component never re-renders again and still has the default state.  this is with most recent next, tamagui etc. (react 18.2.0 rn 0.75.2).

my current workaround is to not use useMedia and use Dimensions from react-native instead.

Ideally, useMedia should have state by the time my component renders.   or pick a better default state based on Dimensions then everything false?

**Comment by alexouterop** [comment]
Getting the same issue here. Might have to use useDimensions.

**Comment by natew** [comment]
Oh I think I know what's happening - media is SSR safe by default on the web. In order to match the server side on the initial render, it will return the same value as the server on first render, and then update with the right values. This is on purpose.

If you set `disableSSR: true` either in the root provider or in the config.settings it will disable this behavior - can someone let me know if that resolves?

In general if you want media queries to be SSR safe you have to go through the style props, double render, or just accept there will be warning logs.

**Comment by natew** [comment]
Latest release has a few more correctness improvements, I think you guys were seeing the SSR behavior still (at least some of you), but the latest changes may help concurrent mode a bit more as well. Can you comment here if it's still breaking? I'll re-open.

**Comment by esinanturan** [comment]
> can confirm this works when using disableSSR: true

Yeah but it is causing other issues on other components with hydration. 
We need a proper way to handle it @natew
