### ISSUE TITLE
Clicking Theme link on tamagui.dev does not work

### ISSUE THREAD

**Issue by Stewartarmbrecht** [tamagui/tamagui#3105]
### Current Behavior

When you click the theme link at the top of the site there is a brief moment where you can see a screen then it turns to an empty page.

### Expected Behavior

A page is displayed.

### Tamagui Version

```markdown
NA
```

### Platform (Web, iOS, Android)

```markdown
Edge and Chrome browser.
```

### Reproduction

```markdown
In the description.
```

**Comment by MarufSharifi** [comment]
Hi @natew,

I'd like to contribute to Tamagui, and this issue seems like a great opportunity for me to get started. I’m happy to investigate and work on this! Let me know if there’s any additional context or guidelines I should keep in mind while addressing it.

Looking forward to your feedback!

Best regards,
Maruf

**Comment by natew** [comment]
Thanks for the offer @MarufSharifi , i think it was just a One issue, the new version seems to have fixed it.

I think it has some bugs with styles on initial load if you go straight to that page, another One issue, but a bit deep. Happy to accept PR there though.
