### ISSUE TITLE
[bug] Custom svg doesn't work with Next.js

### ISSUE THREAD

**Issue by AlandSleman** [tamagui/tamagui#640]
**Describe the bug**
I want to use a custom svg icon with react-native-svg.
It works on mobile(android) and web(react-native-web) it just doesn't work with Next.js.
I tried wrapping the svg with [styled()](https://tamagui.dev/docs/core/styled) and [themed()](https://github.com/tamagui/tamagui/blob/master/packages/lucide-icons/src/themed.tsx), Both didn't work.

I get this Error
```
Server Error
Error: Element type is invalid: expected a string (for built-in components) or 
a class/function (for composite components) but got: object.
```
I also tried @tamagui/react-native-svg same error.

**To Reproduce**
Clone This repo It's just the starter with a svg component:
[https://github.com/AlandSleman/tamagui-svg-issue](https://github.com/AlandSleman/tamagui-svg-issue)

**System Info (please complete the following information):** 
  System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 9.19 GB / 30.70 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 3.3.1 - /usr/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 108.1.46.153
    Chrome: 108.0.5359.124
    Firefox: 108.0
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13
    @manypkg/cli: ^0.19.1 => 0.19.2
    eslint: ^8.21.0 => 8.32.0
    prettier: ^2.7.1 => 2.8.3
    react-native-svg: ^13.8.0 => 13.4.0
    turbo: ^1.4.2 => 1.7.0
    typescript: ^4.7.4 => 4.9.4

**Comment by natew** [comment]
Sorry just outside of scope, can talk on discord about it.

**Comment by alexbchr** [comment]
Trying to do the exact same thing here, how did you end up fixing it?

**Comment by AlandSleman** [comment]
> Trying to do the exact same thing here, how did you end up fixing it?

So funny the problem was just imports try
import { Svg, SvgProps, Path } from 'react-native-svg'
Instead of
import Svg, { SvgProps, Path } from "react-native-svg"
[Check this commit](https://github.com/AlandSleman/tamagui-svg-issue/commit/508984fa882ad277a472b4d6e8486f7c6a865fda)

**Comment by nderscore** [comment]
> Sorry just outside of scope, can talk on discord about it.

@natew Can you share some details about it here for those of us finding this issue in the future? I couldn't find any relevant info by searching the Discord chat logs.

---

Why doesn't `@tamagui/react-native-svg` match `react-native-svg`'s exports? 

The default export there is a reference to the `Svg` component:

https://github.com/software-mansion/react-native-svg/blob/d6975ea9f20f2fefb603f2612fdb3bbc7bf071ca/src/ReactNativeSVG.ts#L152-L153

In `@tamagui/react-native-svg` the default export is an object containing all the named exports of the library:

https://github.com/tamagui/tamagui/blob/8d8efdf99120dd7ba3d1fbf534ac21d06160c358/packages/react-native-svg/src/index.js#L29-L55

It's unexpected and inconvenient that there isn't full parity between both packages, since a lot of existing tooling expects the default export to still be there. For example, `svgr`, a library for generating react components from svg assets and the one linked to in `react-native-svg`'s own docs, uses the default export for `Svg` in their "native" template. 

Since rewriting `react-native-svg` imports is a hidden implementation detail of the Tamagui Next plugin, I expect this will continue to be a source of confusion and wasted debugging cycles for users who will encounter this error.

**Comment by nderscore** [comment]
In case anyone else using `svgr` runs into this issue, here is a workaround implemented a custom svgr plugin which replaces the default `Svg` import with a named import after `svgr` has finished transforming the code:

```js
// svgr.config.js

/** @type {import("@svgr/core").ConfigPlugin} */
const rewriteSvgImport = (code, _config, _state) => {
  return code.replace(/import\s+Svg,\s*\{/, 'import { Svg,');
};

/** @type {import("@svgr/core").Config} */
module.exports = {
  native: true,
  plugins: [
    '@svgr/plugin-jsx',
    rewriteSvgImport
  ],
  // ...
};
```
