### ISSUE TITLE
[bug] vanilla React Native (no web) - react-native-web issues

### ISSUE THREAD

**Issue by criszz77** [tamagui/tamagui#696]
**Describe the bug**
------------

This is a follow up to #688 

While playing around with a vanilla React Native (no web) project, I encountered some issues when integrating Tamagui.

#### **`Bug 1`**: 
Using `<Input />` from Tamagui generates warning.

#### **`Bug 2`**: 
Lots of logs about `react-native-web` not found.

<br>

To Reproduce
------------

1. `npx react-native init MyAppName`
2. Add Tamagui according to docs.

Here is a new reproduction repository with all the commits: https://github.com/criszz77/tamaguibugs

<br>

**Additional context**
-----------

I believe that [setting `TAMAGUI_TARGET` to `native` in the reproduction repo babel.config.js](https://github.com/criszz77/tamaguibugs/blob/master/babel.config.js#L1) is redundant since [`@tamagui/babel-config` seems to already be doing that for you](https://github.com/tamagui/tamagui/blob/master/packages/babel-plugin/src/index.ts#L27) if you omit it. 

<br>

 **Screenshots**
---- 

#### **`Bug 1`**: 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/55203625/218321300-3e5cb8a1-eef5-45f6-9d16-28672b7816de.png">

<br>

#### **`Bug 2`**:
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/55203625/217955486-c8395f2a-bdb7-447f-8435-8afd4869aa44.png">

**Comment by natew** [comment]
A clue is `borderBottomStyle` on native means your TAMAGUI_TARGET is not being picked up as `native`, so there must be some config issue.

**Comment by criszz77** [comment]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/55203625/218332817-8c8affeb-715a-4c63-9c3b-3ac7bcba8525.png">

I'll be investigating it further more next week. Cheers.

**Comment by natew** [comment]
Sorry about this, I know it's frustrating, I'd be happy to add the to the repo and look I want to see why people run into this fairly often and get a good solution in place. Can DM me on Discord if easier.

**Comment by ankit-gl** [comment]
<img width="1292" alt="Screenshot 2023-02-14 at 3 46 52 PM" src="https://user-images.githubusercontent.com/73995394/218706426-6e50fb19-bf34-4a2c-a909-789a95847581.png">
Facing same issue where react-dom is missing

**Comment by iBotPeaches** [comment]
I thought `react-native-web` was just a requirement, since we hit this early on and just accepted it as a requirement.

Our trace looked similar to yours and I tracked it to the static package and some babel [magic](https://github.com/tamagui/tamagui/blob/master/packages/static/src/require.ts#L41). Lost track and didn't want to make invalid claims - since it appeared in my testing that our `react-native` imports were being swapped for `react-native-web` during testing and some metro builds.

We really only needed it for building and couldn't tell outside of that of how it was being invoked, so added it as a dev dependency and called it a day.

I'm only focusing this again, because we are on Tamagui 1.0.16 and its doing well in prod, but time for an RN71 upgrade and thus time to jump to the latest on this.

**Comment by natew** [comment]
On native it should never swap in react-native-web for native, but it may try and require it during build time with he compiler depending on your setup. Not sure but it’s plausible. @iBotPeaches hit me up in chat if you can and I’ll take a look with you.

**Comment by natew** [comment]
RN71 seems to be giving some type issue with circular types somehow. That’s something I’m happy to dig into soon too.

**Comment by natew** [comment]
Done what I can to make packages move to use web, and then the server to de-dupe that better. Also removing react-dom from many packages next release.
