### ISSUE TITLE
`styled(Button)` incompatible with `<Group />`'s borderRadius

### ISSUE THREAD

**Issue by alitnk** [tamagui/tamagui#701]
Button works just fine in `XGroup` and `YGroup`, but when using `styled(Button)` it fails to apply the border radius and it just uses the button's border radius.

It's important to note that this hasn't happened in sandbox (uses Vite) but happened in the documentation app, the `site` app (uses Next.js) - guessing maybe something with the ordering of classes might be involved?

![image](https://user-images.githubusercontent.com/35243344/218512558-95ea10a6-dbcd-46c4-bc23-684fccd11aba.png)
![image](https://user-images.githubusercontent.com/35243344/218512572-fefc63b6-2178-48b2-b2ca-7841f2b5261c.png)

**Comment by idrakimuhamad** [comment]
I'm getting this too. In fact, it seems like using `styled` to extend the button broke some of it internal props.

```jsx
const CustomButton = styled(Button)

<YStack space bg="#dedede" p="$5">
  <Text>Styled Button</Text>
  <XGroup size="$8">
    <XGroup.Item>
      <CustomButton backgroundColor="green">Hello</CustomButton>
    </XGroup.Item>
    <XGroup.Item>
      <CustomButton backgroundColor="green">Hello</CustomButton>
    </XGroup.Item>
    <XGroup.Item>
      <CustomButton backgroundColor="green">Hello</CustomButton>
    </XGroup.Item>
  </XGroup>
  <Text>Tamagui Button</Text>
  <XGroup size="$8">
    <XGroup.Item>
      <Button backgroundColor="green" color="azure">
        Hello
      </Button>
    </XGroup.Item>
    <XGroup.Item>
      <Button backgroundColor="green" color="azure">
        Hello
      </Button>
    </XGroup.Item>
    <XGroup.Item>
      <Button backgroundColor="green" color="azure">
        Hello
      </Button>
    </XGroup.Item>
  </XGroup>
</YStack>
```
![Simulator Screen Shot - iPhone 14 - 2023-03-31 at 10 05 18](https://user-images.githubusercontent.com/1400323/229004401-d3bb45d4-33f3-4420-9b3b-5993b011b3e5.png)

Some prop doesn't do anything on the button itself, like `size` and `background`

```jsx
<YStack space bg="#dedede" p="$5">
  <Text>Styled Button</Text>
  <YGroup>
    <YGroup.Item>
      <CustomButton backgroundColor="green" size="$2">
        Should have size 2
      </CustomButton>
    </YGroup.Item>
    <YGroup.Item>
      <CustomButton backgroundColor="green" size="$8">
        Should have size 8
      </CustomButton>
    </YGroup.Item>
    <YGroup.Item>
      <CustomButton backgroundColor="green" size="$10">
        Should have size 10
      </CustomButton>
    </YGroup.Item>
  </YGroup>
  <Text>Not part of Group</Text>
  <CustomButton backgroundColor="green" size="$10">
    Should have size 10
  </CustomButton>
</YStack>
```

![simulator_screenshot_44CB9A26-CDB1-46B6-AC13-1A6CD2FDE5A2](https://user-images.githubusercontent.com/1400323/229004955-1fbefca4-e961-417b-8f82-061ebdcd9e51.png)

If instead of using `styled`, I just wrapped `Button` inside another button component, it seems to be fine, but the same issue of this thread are still there where the border radius of the button's are not affected by the group size.

**Comment by natew** [comment]
I think we've fixed this in a recent release, let me know if still an issue
