### ISSUE TITLE
Select feature is slow on react native expo

### ISSUE THREAD

**Issue by xwiz** [tamagui/tamagui#793]
Select components takes about 2s to render and have no loading animation.

How to reproduce
Create a screen with up to 30 select items based on this sample: https://tamagui.dev/docs/components/select

https://snack.expo.dev/@patacee/07fc53

Versions
Tamagui 1.7.6

**Comment by mphill** [comment]
This applies to Sheets too.

This is super interesting. We saw lag on an iOS simulator when navigating. Initially, we looked at react-navigation because it seemed to pause BEFORE navigation started.  We just assumed it was related to navigation.  After looking around we determined the` <Select> `on the target screen was slowing down navigation.  

We found if we remove the `Overlay`, we get a speed-up.  if we remove the `<Sheet> `or `<Select>` completely the navigation speed return to normal back to normal.

This only seems to happen on the simulator, physical devices are OK.

@xwiz  try to comment out  `<Sheet.Overlay /> `and see if it's faster.

**Comment by AlexanderHOtt** [comment]
I'm having the same issue on physical devices (iPad Air 2 and Pixel 7)

**Comment by mphill** [comment]
> I'm having the same issue on physical devices (iPad Air 2 and Pixel 7)

Using standalone production builds or expo on the device? We see this issue disappear in production, or maybe the devices are fast enough to mask it…

**Comment by xwiz** [comment]
> This applies to Sheets too.
> 
> This is super interesting. We saw lag on an iOS simulator when navigating. Initially, we looked at react-navigation because it seemed to pause BEFORE navigation started. We just assumed it was related to navigation. After looking around we determined the`<Select>`on the target screen was slowing down navigation.
> 
> We found if we remove the `Overlay`, we get a speed-up. if we remove the `<Sheet> `or `<Select>` completely the navigation speed return to normal back to normal.
> 
> This only seems to happen on the simulator, physical devices are OK.
> 
> @xwiz try to comment out `<Sheet.Overlay /> `and see if it's faster.

Will try this and let you know

**Comment by natew** [comment]
this should be fixed by a lot, we did intense performance work across many areas.

**Comment by Punith-goud** [comment]
`import React, { useState, useEffect } from "react";
import { Check, ChevronDown, ChevronUp } from "@tamagui/lucide-icons";
import { Adapt, Select, Sheet, YStack } from "tamagui";

export const SelectComponent = ({
  id = "default-id",
  label = "Label",
  items = [],
  initialValue = "",
  onValueChange,
  placeholder,
  resetTrigger,
  ...otherProps
}) => {
  const [val, setVal] = useState(initialValue);

  useEffect(() => {
    // Reset the value when the resetTrigger changes
    setVal(initialValue);
  }, [resetTrigger, initialValue]);

  const handleValueChange = (newVal) => {
    setVal(newVal);
    if (onValueChange) {
      onValueChange(newVal);
    }
  };

  return (
    <Select
      id={id}
      value={val}
      onValueChange={handleValueChange}
      disablePreventBodyScroll
      {...otherProps}
    >
      <Select.Trigger
        backgroundColor={"#f5f5f5"}
        borderColor={"#ccc"}
        borderWidth={1}
        iconAfter={ChevronDown}
      >
        <Select.Value color={val ? "#000" : "#999"} placeholder={placeholder} />
      </Select.Trigger>

      <Adapt when="sm" platform="touch">
        <Sheet
          native={!!otherProps.native}
          modal
          dismissOnSnapToBottom
          animationConfig={{
            type: "spring",
            damping: 20,
            mass: 1.2,
            stiffness: 250,
          }}
        >
          <Sheet.Frame>
            <Sheet.ScrollView>
              <Adapt.Contents />
            </Sheet.ScrollView>
          </Sheet.Frame>
          {/* <Sheet.Overlay
            animation="lazy"
            enterStyle={{ opacity: 0 }}
            exitStyle={{ opacity: 0 }}
          /> */}
        </Sheet>
      </Adapt>

      <Select.Content zIndex={200000}>
        <Select.ScrollUpButton
          alignItems="center"
          justifyContent="center"
          position="relative"
          width="100%"
          height="$3"
        >
          <YStack zIndex={10}>
            <ChevronUp size={20} />
          </YStack>
        </Select.ScrollUpButton>

        <Select.Viewport minWidth={200}>
          <Select.Group>
            <Select.Label>{label}</Select.Label>
            {items?.map((item, i) => (
              <Select.Item index={i} key={item.id} value={item}>
                <Select.ItemText>{item.name}</Select.ItemText>
                <Select.ItemIndicator marginLeft="auto">
                  <Check size={16} color={"lightgreen"} fontWeight={"bold"} />
                </Select.ItemIndicator>
              </Select.Item>
            ))}
          </Select.Group>
        </Select.Viewport>

        <Select.ScrollDownButton
          alignItems="center"
          justifyContent="center"
          position="relative"
          width="100%"
          height="$3"
        >
          <YStack zIndex={10}>
            <ChevronDown size={20} />
          </YStack>
        </Select.ScrollDownButton>
      </Select.Content>
    </Select>
  );
};
`
I'm encountering significant performance issues with my Select Component when it's loaded with a large number of items (ranging from 500 to 1000). This problem is severely affecting the mounting and unmounting speed of the component. Additionally, it's drastically slowing down API calls made within the same component context. The slow performance becomes especially noticeable when interacting with the Select Component or executing functions that rely on its state.

Any insights or suggestions to optimize performance for handling such large datasets within the Select Component would be greatly appreciated.

**Comment by ryanvanderpol** [comment]
Sorry to dredge up an old thread, but I don't feel like this issue has been solved. I have a `Select` that displays a list of countries and it causes screen navigation to take 2+ seconds. I've tried replacing the contents of the `Sheet.Frame` with a `FlatList` and it's much faster, but then I get errors about having a `VirtualizedList` inside a `ScrollView` and styling gets messed up.

Is there a recommended way to use a `Select` or `Sheet` with 100+ items? Because out of the box it's way too slow to use.

**Comment by AlexanderHott** [comment]
> Sorry to dredge up an old thread, but I don't feel like this issue has been solved. I have a `Select` that displays a list of countries and it causes screen navigation to take 2+ seconds. I've tried replacing the contents of the `Sheet.Frame` with a `FlatList` and it's much faster, but then I get errors about having a `VirtualizedList` inside a `ScrollView` and styling gets messed up.
> 
> Is there a recommended way to use a `Select` or `Sheet` with 100+ items? Because out of the box it's way too slow to use.

Try https://github.com/Shopify/flash-list, it's a drop-in replacement for `FlatList` that's more performant.

**Comment by mphill** [comment]
If the `<FlashList />` doesn’t work try https://github.com/gorhom/react-native-bottom-sheet

Version 5 is adding web support too. 

We ended up switching to this library to solve our performance issues. 

Good luck.

**Comment by ryanvanderpol** [comment]
@mphill yup, I gave up on Tamagui and switched to that bottom sheet component. it has FlatList support built in and is WAY WAY faster than Tamagui!
