### ISSUE TITLE
[bug] Vanilla React Native - <Toast/> requires burnt (expo modules).

### ISSUE THREAD

**Issue by LunatiqueCoder** [tamagui/tamagui#828]
### Current Behavior

When importing `tamagui` package, it requires `expo-modules` in order to work with vanilla React Native. This happens because Toast (which is a dependency of `tamagui`) uses burnt, and burnt uses expo modules. I believe this issue is similar to the `linear-gradient` one. 

### Expected Behavior

`tamagui` should not force vanilla React Native users to install `expo` only for the `<Toast />` compomnent.

### Tamagui Version

```markdown
Latest
```

### Reproduction
Using [🌘 Luna](https://github.com/LunatiqueCoder/luna) my vanilla React Native template: 

1. `npx react-native init mylunaapp --template @criszz77/luna`
2. Update Tamagui to latest
3. `yarn start` 
4. `yarn ios`

We also have an open issue: https://github.com/LunatiqueCoder/luna/issues/75

**Comment by aminta** [comment]
Same problem here

**Comment by natew** [comment]
Next patch release moves the dep into `devDependencies` so it's fully optional to install. Thanks for the report. Close if fixed.

**Comment by LunatiqueCoder** [comment]
Hey @natew @alitnk, it seems that it's still reproducing. 🙈 Sorry for the late response.

**Comment by alitnk** [comment]
Hey @LunatiqueCoder, we removed it from deps altogether. Try v1.9.18, but feel free to re-open if the issue persists.

**Comment by LunatiqueCoder** [comment]
Hey @alitnk @natew 

Yes, I tried it, but it still happens on v1.9.18. 😔 I believe the reproduction steps should work. Unfortunately, I don't have permissions to reopen.

**Comment by nderscore** [comment]
I posted some more details in #892 

Concerningly, this error happens even without importing or using the `<Toast />` at all 🤔 

---

> we removed it from deps altogether

This isn't a valid fix. Since `burnt` is a required dependency to use toasts, it should at least be listed in `peerDependencies`.

The `@tamagui/toast` package should have a required peer dependency on `burnt`:

```json
// ./packages/toast/package.json
"peerDependencies": {
  "burnt": "..."
},
"devDependencies": {
  "burnt": "..."
}
```

And the `tamagui` package should have it listed as optional (ince you don't necessarily need to use the toast from the package:

```json
// ./packages/tamagui/package.json
"peerDependencies": {
  "burnt": "..."
},
"peerDependenciesMeta": {
  "burnt": {
    "optional": true
  }
},
"devDependencies": {
  "burnt": "..."
}
```

**Comment by natew** [comment]
@nderscore the problem is (as I understand it) the second you add it to any `peerDependencies` React Native seems to break builds until you actually install the dependency.

`peerDependenciesMeta` seems like the right solution, but does RN respect it? If so happy to make the change.

We do have docs instructing how to install it since you *have* to add it to your app, even if we depend on it, since RN *also* doesn't install native sub-dependencies for you automatically.

**Comment by nderscore** [comment]
@natew React Native builds are already broken without the dependency being declared.

My project doesn't use the toast component at all (my UI package doesn't even re-export the toast or its related functions). 

Simply importing `tamagui` triggers a `Unable to resolve "burnt"` error in the current version (#892)

**Comment by lostpebble** [comment]
Is there a reason why this dependency isn't listed inside `dependencies` ? Seems similar to https://github.com/tamagui/tamagui/issues/884 - if a package needs a dependency for operation, it should be listed in `dependencies` - not `peerDependencies` or `devDependencies`. I think `peerDependencies` still expects the user to actually have that dependency in their project manually or through some other means.

**Comment by natew** [comment]
Because it makes no difference you'd have to install it anyway in your app dir, because RN doesn't install native deps of sub-deps automatically (correct me if I'm wrong).

I mean we could remove toasts from `tamagui`, and just make them installable through the separate package. I don't mind that. Thoughts?

**Comment by nderscore** [comment]
If metro doesn't support conditional imports and RN autolinking doesn't work for sub-deps, it probably makes sense to split toasts into a separate package with `burnt` listed in its peer-deps.

Since `burnt` includes custom native code, its also incompatible with vanilla Expo Go. That might be another reason to make toasts an opt-in feature.

**Comment by alitnk** [comment]
> it probably makes sense to split toasts into a separate package with `burnt` listed in its peer-deps.

Already doing it! https://github.com/tamagui/tamagui/pull/917
