### ISSUE TITLE
[bug] fontSize not converted to valid size overriden from a variant

### ISSUE THREAD

**Issue by foyarash** [tamagui/tamagui#845]
Considering the following component:

```
import { styled, Text as TamaguiText } from "@tamagui/core";

export const Heading = styled(TamaguiText, {
    name: "Heading",
  color: "$color",

variants: {
    type: {
      "myVariant": {
        fontFamily: "$myFont",
        fontSize: "$24",
        lh: "$24",
        fow: "$bold"
      },
    }
  } as const
})
```

If i do
```
 <Heading type="myVariant" fontSize="$20">
        H1
      </Heading>
```
it will not convert `fontSize="$20"` to a valid font size, unless in explicitly provide a font family to the props.

**Expected behavior**

The fontSize prop should just override the fontSize from the variant

**Comment by natew** [comment]
Woah this one is actually super interesting... its the first case i've found where our loop backwards over props causes issues. Because we apply styles as `last-prop-wins`, so we loop backwards over them. But in this case the variant before it sets up the fontFamily... 

I think we can actually loop forwards, it just means instead of skipping values we overwrite... I was hoping to knock this one out in a few minutes but likely takes 20-30 and I have to head out soon but I think the fix is:

1. First, we should really flesh out our tests - we need actual in-browser tests of variant + psuedo + responsive + font etc etc
2. In `getSplitStyles` change the backwards loop to forwards see `// loop backwards so we can skip already-used props`
3. Probably can remove `usedKeys` entirely?? It's used in a bunch of places but I think we wouldn't need it, this may actually net be better for perf then..
4. As we move forwards in the props we should constantly be on the lookout for `fontFamily` as it's "special" and determines what the props after it will use to lookup in the design system
5. To see how that works see `getToken` in `createPropMapper.ts`  specifically the line `valOrVar = fontsParsed[fontFamily]?.[fontShorthand[key] || key]?.[value] || value`, we'll need to actually have some `let` variable in `getSplitStyles` that is always getting the latest `fontFamily` and then passing it back into the propMapper

@alitnk this is a pretty decent one, I can take it but maybe interesting to dive into the internals.

**Comment by natew** [comment]
Also temporary fix is to put the variant prop *after* fontSize in order... but once this is fixed actually the reverse will be true - you have to set fontSize before...

Which is interesting. I've been a big proponent of order mattering for styles, it makes variants deterministic and is actually just strictly necessary. 

But if we want "fontFamily" to be sort of special, we may want instead of the above changes to do:

1. Keep the backwards loop....
2. Keep track of the ultimate fontFamily value in getSplitStyles
3. Keep track of all font related properties... this is janky
4. At the end of the loop, we'd have to then go back and fill in the values

I think this is just straight up not desirable, it's really complex having to loop over it again...

**Comment by alitnk** [comment]
>  but once this is fixed actually the reverse will be true - you have to set fontSize before...

So I think ultimately changing the loop's direction fixes this issue but introduces another and we need to keep track of the font related properties nonetheless.
