### ISSUE TITLE
Invalid Hook Call Warning errors when using TamaguiProvider 

### ISSUE THREAD

**Issue by griffithcaleb** [tamagui/tamagui#874]
### Current Behavior

Here is what I currently have at the root of my application. 

```
const App = () => (
  <TamaguiProvider config={config} defaultTheme="light" disableInjectCSS>
    <QueryClientProvider client={queryClient}>
      <div />
    </QueryClientProvider>
  </TamaguiProvider>
);

document.addEventListener('DOMContentLoaded', () => {
  createRoot(document.getElementById('entry')).render(<App />);
});
```

Unfortunately when rendering I am receiving the following: 
`Uncaught TypeError: Cannot read properties of null (reading 'useEffect')
`
https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html

It seems like the provider is trying to call react hooks and a hook misuse error is being fired. 

- I can confirm that I have matching versions (18.0.2) of `react` and `react-dom` . 
- I can confirm that my config is being imported correctly.

Any help would be greatly appreciated. 

### Tamagui Version

```markdown
{
  "name": "@somename/components",
  "version": "1.0.0",
  "sideEffects": [
    "*.css"
  ],
  "private": true,
  "types": "./types/index",
  "main": "./dist/cjs",
  "module:jsx": "src",
  "files": [
    "types",
    "dist"
  ],
  "scripts": {
    "build": "tamagui-build",
    "watch": "tamagui-build --watch"
  },
  "dependencies": {
    "@tamagui/animations-react-native": "1.9.18",
    "@tamagui/font-inter": "1.9.18",
    "@tamagui/react-native-media-driver": "1.9.18",
    "@tamagui/shorthands": "1.9.18",
    "@tamagui/themes": "1.9.18",
    "react-dom": "^18.2.0",
    "react": "^18.2.0",
    "react-native-web": "^0.19.1",
    "tamagui": "1.9.18"
  },
  "devDependencies": {
    "@tamagui/build": "1.9.18",
    "@types/fs-extra": "^9.0.13",
    "chokidar": "^3.5.2",
    "esbuild": "^0.17.5",
    "execa": "^5.0.0",
    "fast-glob": "^3.2.11",
    "fs-extra": "^11.1.0",
    "lodash.debounce": "^4.0.8",
    "typescript": "^4.7.4"
  }
}
```

### Reproduction

```markdown
see code above
```

**Comment by natew** [comment]
Apologize for closing but we need a repro and you can re-open.

**Comment by griffithcaleb** [comment]
`yarn add  burnt --dev` worked for me

**Comment by Victor-ARC** [comment]
I'm getting this same issue.
But, I'm on React Native "0.74.0".

As for the repro, literally I just created an empty project (without EXPO or any other framework) and added my `tamagui.config.ts` and a TamaguiProvider with the `config` props set to the export of `tamagui.config.ts` (which is the result of calling `createTamagui`as the docs specify). I'm not even using the Tamagui config from `@tamagui/config`.

What I've done so far:
- Clean Android build folder (with `./gradlew clean` command)
- Reinstall NPM packages.
- Reset cache on Metro command (`--reset-cache` passed to `npm run start`).
- Uninstall/reinstall the app.

So far, also, only removing the provider removes the error. I have installed `react : "18.2.0"` and `@tamagui/core : "^1.116.9"`.

Here's the console Error:
```
 ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. Component Stack:
 ERROR  TypeError: Cannot read property 'useState' of null

This error is located at:
    in UnmountedClassName
    in TamaguiProvider (created by <some component ref>)
    in <some component ref>(created by Connect(<some component ref>))
    in Connect(<some component ref>) (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in listup(RootComponent), js engine: hermes
```

What strikes me as odd is that it says that the top component is `UnmountedClassName`, which I have never ever heard of before.

Also, the LogBox gives a link to a Tamagui file at this location: `.../<project_dir>/node_modules/@tamagui/web/node_modules/react/cjs/react.development.js`. But I'm currently just building for Android, not even iOS. Why would it throw errors from web?

It's worth mentioning that I also had `'tamagui'` installed before, then I cleaned the deps and just installed `'@tamagui/core'`, since I realized I didn't need the whole UI kit as I'm trying to develop my own components.

Another thing I tried just before this error appeared was to create a `styled` view (with the Tamagui View component) which is used inside the same file in an exported component that has the following hierarchy:
```
import { styled, View } from '@tamagui/core';
import { SafeAreaView } from 'react-native-safe-area-context';

const Background = styled(View, {...});

const Wrapper = (props) => {
    return (
        <Background>
            <SafeAreaView>{props.children}</SafeAreaView>
        </BacKground>
    );
};

export default Wrapper;
```
What I wanted to do is to have a Styled backdrop for the whole app which would change color upon changing the theme. Right after I did this, it send a weird error which I didn't copy (obviously) and then it just started to give the error mentioned before. It's stuck there. So I started removing components and the only thing left is just the Tamagui provider and the error persists.

Is this information enough?

**Comment by Victor-ARC** [comment]
A lot happened in ~40 min.
Adding :
```
"overrides": {
    "react": "18.2.0"
}
```
Works like a charm. For some reason it seems Tamagui and NPM are referencing different React versions.
Still, it'd be nice not to have to do this.

Hope this helps someone!

**Comment by sample-usr** [comment]
@Victor-ARC Thanks, just upgrade to expo 52 and had the same issue with Tamagui, adding the override in package.json fixed it for me as well.
